blog_db:
  image: mariadb:latest
  container_name: blog_db
  hostname: blog-db
  environment:
    - MYSQL_ROOT_PASSWORD=xxxxxxx
    - MYSQL_DATABASE=xxxxx
  restart: always
  volumes:
    - /srv/containers/blog_db:/var/lib/mysql
blog_web:
  container_name: blog
  hostname: blog
  image: ghost-blog
  restart: always
  ports:
   - "2368:2368"
  links:
    - blog_db
  volumes:
    - /srv/containers/blog:/srv/ghost/content
  environment:
    - EMAIL_USER=xxxx@xxxxxxx.xx
    - EMAIL_PASS=xxxxxxxxxxxxxxx
